# Generated by Django 3.1.3 on 2021-12-22 10:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_name', models.CharField(max_length=50)),
                ('week_count', models.IntegerField()),
                ('day_count', models.IntegerField()),
                ('exercise_1', models.CharField(max_length=100)),
                ('exercise_1_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise_2', models.CharField(max_length=100)),
                ('exercise_2_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise_3', models.CharField(max_length=100)),
                ('exercise_3_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise_4', models.CharField(max_length=100)),
                ('exercise_4_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaxValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=100, verbose_name='Name of Exercise')),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise_Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name of Exercise')),
                ('muscle', models.CharField(choices=[('legs', 'Legs'), ('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('core', 'Core'), ('calves', 'Calves')], default='chest', max_length=50, verbose_name='Name of Musclegroup')),
                ('high_range', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('mid_range', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('low_range', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
