# Generated by Django 3.1.3 on 2021-11-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_pool',
            name='track',
            field=models.BooleanField(blank=True, null=True, verbose_name='Track Performance'),
        ),
        migrations.AlterField(
            model_name='exercise_pool',
            name='max_calc',
            field=models.BooleanField(blank=True, null=True, verbose_name='Include in Max-Calculator'),
        ),
    ]
