# Generated by Django 3.1.3 on 2021-11-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20211106_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise_pool',
            old_name='track',
            new_name='track_perform',
        ),
    ]
