# Generated by Django 3.1.3 on 2021-12-08 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20211208_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_pool',
            name='timestamp',
            field=models.DateTimeField(default="2021-12-10 11:44:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise_pool',
            name='high_range',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='exercise_pool',
            name='low_range',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='exercise_pool',
            name='mid_range',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='exercise_pool',
            name='muscle',
            field=models.CharField(choices=[('legs', 'Legs'), ('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('core', 'Core'), ('calves', 'Calves')], default='chest', max_length=50, verbose_name='Name of Musclegroup'),
        ),
    ]
