# Generated by Django 3.1.3 on 2021-12-28 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20211225_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_pool',
            name='high_range',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='exercise_pool',
            name='low_range',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='exercise_pool',
            name='mid_range',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
