# Generated by Django 3.1.3 on 2021-12-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20211228_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='max_weight_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
