# Generated by Django 3.1.3 on 2021-12-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20211212_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise_pool',
            name='timestamp',
        ),
    ]
