# Generated by Django 3.1.3 on 2021-12-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20211228_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='exercise_1_set_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='exercise_1_set_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='exercise_1_set_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='exercise_1_set_4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
