# Generated by Django 3.1.3 on 2021-12-19 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0008_remove_exercise_pool_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_name', models.CharField(max_length=50)),
                ('week', models.IntegerField()),
                ('day', models.IntegerField()),
                ('exercise_1', models.CharField(max_length=100)),
                ('exercise_1_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
