# Generated by Django 3.1.3 on 2021-12-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20211228_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_pool',
            name='muscle',
            field=models.CharField(choices=[('legs', 'Legs'), ('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('core', 'Core'), ('calves', 'Calves')], default='chest', max_length=50, verbose_name='Musclegroup'),
        ),
    ]
